server:
  port: 8081
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 182.92.176.70
    port: 3306
    database: video_web
    username: root
    password: nhb2438012195

minio:
  endpoint: http://182.92.176.70:9000
  access-key: root
  secret-key: nhb2438012195
  bucket-name: public

redis:
  host: 182.92.176.70
  port: 6379
  password: nhb2438012195

rabbitmq:
  host: 182.92.176.70
  port: 5672
  username: root
  password: nhb2438012195